const accountDb=()=>window.afiliaSupabase||null;
const accountEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let accountBusy=false;
let accountUid=null;
function accountModal(html){const body=document.getElementById('modalBody'),root=document.getElementById('modal');if(!body||!root)return;body.innerHTML=html;root.classList.add('show')}
function accountClose(){document.getElementById('modal')?.classList.remove('show')}
async function accountState(){const db=accountDb();if(!db)return null;const{data:{session}}=await db.auth.getSession();if(!session?.user)return null;const uid=session.user.id;const{data:connections=[],error}=await db.from('whatsapp_connections').select('id,status,phone_masked,session_secret_configured,last_connected_at,last_heartbeat_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(1);if(error)throw error;const c=connections[0]||null;let groups=0,enabled=0;if(c){const [all,on]=await Promise.all([db.from('whatsapp_group_refs').select('*',{count:'exact',head:true}).eq('user_id',uid).eq('connection_id',c.id),db.from('whatsapp_group_refs').select('*',{count:'exact',head:true}).eq('user_id',uid).eq('connection_id',c.id).eq('is_enabled',true)]);if(all.error)throw all.error;if(on.error)throw on.error;groups=all.count||0;enabled=on.count||0}return{session,user:session.user,connection:c,groups,enabled}}
function hasWhatsData(s){return !!(s?.connection&&(s.connection.status!=='disconnected'||s.connection.session_secret_configured||s.groups>0))}
function updateAvatar(user){const avatar=document.querySelector('.profile');if(!avatar||!user)return;const name=user.user_metadata?.name||user.email?.split('@')[0]||'U';const initial=String(name).trim().charAt(0).toUpperCase()||'👤';avatar.textContent=initial;avatar.title=`Conta: ${name}`;avatar.setAttribute('aria-label',`Minha conta: ${name}`)}
function announceUser(user){if(!user)return;const changed=accountUid&&accountUid!==user.id;accountUid=user.id;document.body.dataset.afiliaUser=user.id;updateAvatar(user);window.dispatchEvent(new CustomEvent('afilia:user-changed',{detail:{userId:user.id,changed}}));if(changed){window.refreshWaCard?.();window.dispatchEvent(new Event('hashchange'))}}
async function openAccountSession(){try{const s=await accountState();if(!s){location.replace('./auth.html');return}announceUser(s.user);const name=s.user.user_metadata?.name||s.user.email?.split('@')[0]||'Usuário';const c=s.connection;const connected=c?.status==='connected';const waLabel=connected?'Conectado':c?.status==='pairing'?'Pareando':c?.status==='degraded'?'Reconectando':'Desconectado';accountModal(`<h3>Minha conta</h3><div class="profileBlock"><div class="avatarBig">${accountEsc(String(name).trim().charAt(0).toUpperCase()||'👤')}</div><b>${accountEsc(name)}</b><span>${accountEsc(s.user.email||'')}</span></div><div class="notice ${connected?'good':''}"><strong>WhatsApp: ${accountEsc(waLabel)}</strong><br>${connected&&c?.phone_masked?accountEsc(c.phone_masked)+' • ':''}${s.groups} grupo(s) desta conta • ${s.enabled} habilitado(s).</div><div class="notice good"><strong>Conta isolada por usuário</strong><br>Ao sair do Afilia, seus grupos e sua sessão do WhatsApp continuam salvos nesta conta. Ao entrar novamente, eles reaparecem. Outro usuário vê somente os próprios dados.</div><div class="actions">${hasWhatsData(s)?'<button class="btn danger full" onclick="disconnectWhatsAppAccount()">Desconectar WhatsApp</button>':''}<button class="btn secondary full" onclick="closeModal()">Fechar</button></div><button class="btn danger full" style="margin-top:9px" onclick="logoutAfiliaIsolated()">Sair do Afilia</button>`)}catch(e){console.error('account modal',e);accountModal(`<h3>Minha conta</h3><div class="notice warn"><strong>Não consegui carregar a conta.</strong><br>Tente novamente.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}}
async function disconnectWhatsAppAccount(){if(accountBusy)return false;const db=accountDb();if(!db)return false;const s=await accountState();if(!s)return false;if(!hasWhatsData(s)){await openAccountSession();return true}if(!confirm('Desconectar o WhatsApp desta conta? Esta ação apaga a sessão vinculada e os grupos salvos deste usuário. Para usar novamente será necessário escanear um novo QR.'))return false;accountBusy=true;try{accountModal(`<h3>Desconectando WhatsApp</h3><div class="notice"><strong>Encerrando somente o WhatsApp…</strong><br>Sua conta Afilia continuará conectada.</div>`);const{data,error}=await db.functions.invoke('whatsapp-disconnect',{body:{connection_id:s.connection.id}});if(error)throw error;if(!data?.ok)throw new Error(data?.detail||data?.error||'disconnect_failed');accountModal(`<h3>WhatsApp desconectado</h3><div class="notice good"><strong>✅ Sessão removida.</strong><br>Os grupos do WhatsApp desta conta foram apagados. Sua conta Afilia continua ativa.</div><button class="btn primary full" onclick="openAccountSession()">Voltar</button>`);window.refreshWaCard?.();return true}catch(e){console.error('whatsapp disconnect',e);accountModal(`<h3>Falha ao desconectar</h3><div class="notice warn"><strong>Não consegui confirmar a remoção.</strong><br>Nenhuma outra conta foi alterada.</div><div class="actions"><button class="btn primary full" onclick="disconnectWhatsAppAccount()">Tentar novamente</button><button class="btn secondary full" onclick="openAccountSession()">Voltar</button></div>`);return false}finally{accountBusy=false}}
async function logoutAfiliaIsolated(){if(accountBusy)return;const db=accountDb();if(!db)return;if(!confirm('Sair desta conta Afilia? O WhatsApp e os grupos permanecerão salvos nesta conta para quando você entrar novamente.'))return;accountBusy=true;try{accountModal(`<h3>Saindo da conta</h3><div class="notice"><strong>Encerrando somente o acesso ao Afilia…</strong><br>WhatsApp, grupos, templates e histórico permanecem vinculados a este usuário.</div>`);accountUid=null;delete document.body.dataset.afiliaUser;window.dispatchEvent(new CustomEvent('afilia:user-cleared'));await db.auth.signOut({scope:'local'});location.replace('./auth.html?loggedout=1')}catch(e){console.error('logout',e);accountBusy=false;accountModal(`<h3>Não consegui sair</h3><div class="notice warn"><strong>Sessão ainda ativa.</strong><br>Tente novamente.</div><button class="btn primary full" onclick="logoutAfiliaIsolated()">Tentar novamente</button>`)} }
window.openAccountSession=openAccountSession;
window.openProfile=openAccountSession;
window.disconnectWhatsAppAccount=disconnectWhatsAppAccount;
window.logoutAfiliaIsolated=logoutAfiliaIsolated;
window.logoutAfilia=logoutAfiliaIsolated;
function wireAvatar(){const avatar=document.querySelector('.profile');if(!avatar)return;avatar.setAttribute('role','button');avatar.setAttribute('tabindex','0');avatar.onclick=e=>{e.preventDefault();e.stopPropagation();openAccountSession()};avatar.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openAccountSession()}}}
async function bootAccountSession(){wireAvatar();const db=accountDb();if(!db)return;const{data:{session}}=await db.auth.getSession();if(!session?.user){location.replace('./auth.html');return}announceUser(session.user);db.auth.onAuthStateChange((event,next)=>{if(event==='SIGNED_OUT'||!next?.user){accountUid=null;delete document.body.dataset.afiliaUser;window.dispatchEvent(new CustomEvent('afilia:user-cleared'));return}announceUser(next.user)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootAccountSession);else bootAccountSession();
