const accountDb=()=>window.afiliaSupabase||null;
const accountEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let accountBusy=false;
function accountModal(html){const body=document.getElementById('modalBody'),root=document.getElementById('modal');if(!body||!root)return;body.innerHTML=html;root.classList.add('show')}
async function accountState(){const db=accountDb();if(!db)return null;const{data:{session}}=await db.auth.getSession();if(!session?.user)return null;const uid=session.user.id;const{data:connections=[],error}=await db.from('whatsapp_connections').select('id,status,phone_masked,session_secret_configured,last_connected_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(1);if(error)throw error;const c=connections[0]||null;let groups=0;if(c){const r=await db.from('whatsapp_group_refs').select('*',{count:'exact',head:true}).eq('user_id',uid).eq('connection_id',c.id);if(r.error)throw r.error;groups=r.count||0}return{session,user:session.user,connection:c,groups}}
function hasWhatsData(s){return !!(s?.connection&&(s.connection.status!=='disconnected'||s.connection.session_secret_configured||s.groups>0))}
async function openAccountSession(){try{const s=await accountState();if(!s){location.replace('./auth.html');return}const name=s.user.user_metadata?.name||s.user.email?.split('@')[0]||'Usuário';const c=s.connection;const connected=c?.status==='connected';const waLabel=connected?'Conectado':c?.status==='pairing'?'Pareando':c?.status==='degraded'?'Reconectando':'Desconectado';accountModal(`<h3>Minha conta</h3><div class="profileBlock"><div class="avatarBig">👤</div><b>${accountEsc(name)}</b><span>${accountEsc(s.user.email||'')}</span></div><div class="notice ${connected?'good':''}"><strong>WhatsApp: ${accountEsc(waLabel)}</strong><br>${connected&&c?.phone_masked?accountEsc(c.phone_masked)+' • ':''}${s.groups} grupo(s) vinculados a esta conta Afilia.</div><div class="notice"><strong>Isolamento por usuário</strong><br>Esta conta enxerga somente a própria sessão, grupos e envios do WhatsApp.</div><div class="actions">${hasWhatsData(s)?'<button class="btn danger full" onclick="disconnectWhatsAppAccount()">Desconectar WhatsApp</button>':''}<button class="btn secondary full" onclick="closeModal()">Fechar</button></div><button class="btn danger full" style="margin-top:9px" onclick="logoutAfiliaIsolated()">Sair da conta</button>`)}catch(e){console.error('account modal',e);accountModal(`<h3>Minha conta</h3><div class="notice warn"><strong>Não consegui carregar a conta.</strong><br>Tente novamente.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}}
async function disconnectOwnedWhatsApp({ask=true,render=true}={}){if(accountBusy)return false;const db=accountDb();if(!db)return false;const s=await accountState();if(!s)return false;if(!hasWhatsData(s)){if(render)await openAccountSession();return true}if(ask&&!confirm('Desconectar o WhatsApp desta conta? A sessão vinculada, os grupos e a fila automática do WhatsApp serão removidos. Para usar novamente será necessário escanear um novo QR.'))return false;accountBusy=true;try{if(render)accountModal(`<h3>Desconectando WhatsApp</h3><div class="notice"><strong>Encerrando a sessão vinculada…</strong><br>Removendo os grupos e credenciais somente desta conta.</div>`);const{data,error}=await db.functions.invoke('whatsapp-disconnect',{body:{connection_id:s.connection.id}});if(error)throw error;if(!data?.ok)throw new Error(data?.detail||data?.error||'disconnect_failed');const check=await accountState();if(hasWhatsData(check))throw new Error('cleanup_not_confirmed');if(render)accountModal(`<h3>WhatsApp desconectado</h3><div class="notice good"><strong>✅ Conta zerada.</strong><br>A sessão e os grupos deste usuário foram removidos. Um novo vínculo exigirá QR Code.</div><button class="btn primary full" onclick="openAccountSession()">Voltar à conta</button>`);window.refreshWaCard?.();return true}catch(e){console.error('whatsapp disconnect',e);if(render)accountModal(`<h3>Falha ao desconectar</h3><div class="notice warn"><strong>O logout foi interrompido por segurança.</strong><br>Não vou sair da conta enquanto a limpeza do WhatsApp não for confirmada.</div><div class="actions"><button class="btn primary full" onclick="disconnectWhatsAppAccount()">Tentar novamente</button><button class="btn secondary full" onclick="openAccountSession()">Voltar</button></div>`);return false}finally{accountBusy=false}}
async function disconnectWhatsAppAccount(){return disconnectOwnedWhatsApp({ask:true,render:true})}
async function logoutAfiliaIsolated(){if(accountBusy)return;const db=accountDb();if(!db)return;const s=await accountState();if(!s){location.replace('./auth.html');return}const msg=hasWhatsData(s)?'Ao sair, o Afilia também desconectará este WhatsApp e removerá todos os grupos desta conta. Na próxima entrada será necessário ler um novo QR. Continuar?':'Sair desta conta Afilia?';if(!confirm(msg))return;accountModal(`<h3>Saindo da conta</h3><div class="notice"><strong>Protegendo sua sessão…</strong><br>${hasWhatsData(s)?'Primeiro vou desconectar o WhatsApp e zerar os grupos deste usuário.':'Finalizando sua sessão Afilia.'}</div>`);if(hasWhatsData(s)){const ok=await disconnectOwnedWhatsApp({ask:false,render:false});if(!ok){accountModal(`<h3>Não foi possível sair</h3><div class="notice warn"><strong>A limpeza do WhatsApp não foi confirmada.</strong><br>Por segurança, sua sessão Afilia continua aberta. Tente novamente.</div><div class="actions"><button class="btn primary full" onclick="logoutAfiliaIsolated()">Tentar novamente</button><button class="btn secondary full" onclick="openAccountSession()">Voltar</button></div>`);return}}accountModal(`<h3>Saindo da conta</h3><div class="notice good"><strong>✅ WhatsApp limpo.</strong><br>Finalizando o acesso ao Afilia…</div>`);await db.auth.signOut();location.replace('./auth.html?loggedout=1')}
window.openAccountSession=openAccountSession;
window.openProfile=openAccountSession;
window.disconnectWhatsAppAccount=disconnectWhatsAppAccount;
window.logoutAfiliaIsolated=logoutAfiliaIsolated;
window.logoutAfilia=logoutAfiliaIsolated;
function wireAvatar(){const avatar=document.querySelector('.profile');if(!avatar)return;avatar.setAttribute('role','button');avatar.setAttribute('tabindex','0');avatar.onclick=e=>{e.preventDefault();openAccountSession()};avatar.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openAccountSession()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wireAvatar);else wireAvatar();
