await import('./app-core.js?v=053');
await import('./templates.js?v=002');
await import('./mirror.js?v=003');
await import('./whatsapp-ui-fix.js?v=053');

let mirrorGroupUxBusy=false;
let mirrorGroupUxOrder=new Map();
let mirrorGroupUxFetchedAt=0;
const mgDb=()=>window.afiliaSupabase||null;
const mgSleep=ms=>new Promise(r=>setTimeout(r,ms));
async function mgUid(){const db=mgDb();if(!db)return null;const{data:{session}}=await db.auth.getSession();return session?.user?.id||null}
function mgToast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
async function mgLoadOrder(force=false){if(!force&&Date.now()-mirrorGroupUxFetchedAt<10000&&mirrorGroupUxOrder.size)return;const db=mgDb(),uid=await mgUid();if(!db||!uid)return;const{data,error}=await db.from('whatsapp_group_refs').select('id,created_at,updated_at').eq('user_id',uid).eq('name_status','verified').order('updated_at',{ascending:false}).order('created_at',{ascending:false});if(error){console.warn('mirror_group_order_error',error);return}mirrorGroupUxOrder=new Map((data||[]).map((g,i)=>[g.id,i]));mirrorGroupUxFetchedAt=Date.now()}
function mgRank(id){return mirrorGroupUxOrder.has(id)?mirrorGroupUxOrder.get(id):999999}
function mgReorderVisibleGroups(){const source=document.getElementById('mirSource');if(source){const placeholder=[...source.options].find(o=>!o.value)||null,selected=source.value,options=[...source.options].filter(o=>o.value).sort((a,b)=>mgRank(a.value)-mgRank(b.value));if(placeholder)source.appendChild(placeholder);for(const o of options)source.appendChild(o);source.value=selected}const host=document.getElementById('mirTargets');if(host){const rows=[...host.querySelectorAll('.mirrorCheckRow')];rows.sort((a,b)=>mgRank(a.querySelector('.mirTarget')?.value||'')-mgRank(b.querySelector('.mirTarget')?.value||''));for(const row of rows)host.appendChild(row)}}
function mgSnapshotForm(){return{name:document.getElementById('mirName')?.value||'',source:document.getElementById('mirSource')?.value||'',targets:[...document.querySelectorAll('.mirTarget:checked')].map(x=>x.value),platforms:[...document.querySelectorAll('.mirPlatform:checked')].map(x=>x.value),start:document.getElementById('mirStart')?.value||'00:00',end:document.getElementById('mirEnd')?.value||'23:59',interval:document.getElementById('mirInterval')?.value||'0',device:document.getElementById('mirDevice')?.value||'',active:!!document.getElementById('mirActive')?.checked,creating:/Criar novo espelhamento/i.test(document.getElementById('modalBody')?.textContent||'')}}
async function mgWaitForForm(timeout=5000){const end=Date.now()+timeout;while(Date.now()<end){if(document.getElementById('mirSource'))return true;await mgSleep(100)}return false}
function mgRestoreForm(s){const set=(id,val)=>{const el=document.getElementById(id);if(el)el.value=val};set('mirName',s.name);set('mirSource',s.source);set('mirStart',s.start);set('mirEnd',s.end);set('mirInterval',s.interval);set('mirDevice',s.device);const a=document.getElementById('mirActive');if(a)a.checked=s.active;if(typeof window.renderMirrorTargets==='function')window.renderMirrorTargets();for(const el of document.querySelectorAll('.mirTarget'))el.checked=s.targets.includes(el.value);for(const el of document.querySelectorAll('.mirPlatform'))if(!el.disabled)el.checked=s.platforms.includes(el.value);if(typeof window.updateMirrorTargetCounter==='function')window.updateMirrorTargetCounter();mgReorderVisibleGroups()}
async function refreshMirrorWhatsAppGroups(){if(mirrorGroupUxBusy)return;const db=mgDb(),uid=await mgUid();if(!db||!uid){mgToast('Sessão do Afilia não encontrada');return}const button=document.getElementById('mirRefreshGroups'),state=mgSnapshotForm();mirrorGroupUxBusy=true;if(button){button.disabled=true;button.textContent='↻ Sincronizando grupos...'}try{let connectionId=null;if(state.source){const{data}=await db.from('whatsapp_group_refs').select('connection_id').eq('id',state.source).eq('user_id',uid).maybeSingle();connectionId=data?.connection_id||null}if(!connectionId){const{data,error}=await db.from('whatsapp_connections').select('id,status,session_secret_configured,last_heartbeat_at,updated_at').eq('user_id',uid).eq('session_secret_configured',true).order('last_heartbeat_at',{ascending:false,nullsFirst:false}).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;connectionId=data?.id||null}if(!connectionId)throw new Error('Nenhum WhatsApp vinculado para sincronizar');mgToast('Sincronizando grupos do WhatsApp...');const{data,error}=await db.functions.invoke('whatsapp-sync-groups',{body:{connection_id:connectionId}});if(error)throw error;if(data?.error)throw new Error(data.detail||data.error);await mgLoadOrder(true);if(state.creating&&typeof window.newMirrorRule==='function'){window.newMirrorRule();if(await mgWaitForForm()){mgRestoreForm(state);await mgLoadOrder(true);mgReorderVisibleGroups()}}mgToast(`Grupos atualizados${Number(data?.groups)>=0?` • ${data.groups} encontrados`:''}`)}catch(e){console.error('mirror_group_sync_error',e);mgToast(String(e?.message||'Não foi possível atualizar os grupos'))}finally{mirrorGroupUxBusy=false;const b=document.getElementById('mirRefreshGroups');if(b){b.disabled=false;b.textContent='↻ Atualizar grupos do WhatsApp'}}}
window.refreshMirrorWhatsAppGroups=refreshMirrorWhatsAppGroups;
async function mgEnhanceForm(){const source=document.getElementById('mirSource');if(!source)return;if(!document.getElementById('mirRefreshGroups')){const btn=document.createElement('button');btn.id='mirRefreshGroups';btn.type='button';btn.className='btn secondary full';btn.style.margin='0 0 10px';btn.textContent='↻ Atualizar grupos do WhatsApp';btn.onclick=refreshMirrorWhatsAppGroups;const label=source.previousElementSibling;source.parentNode.insertBefore(btn,label||source)}await mgLoadOrder();mgReorderVisibleGroups()}
let mgTimer=null;const mgObserver=new MutationObserver(()=>{clearTimeout(mgTimer);mgTimer=setTimeout(()=>mgEnhanceForm().catch(console.warn),80)});if(document.body)mgObserver.observe(document.body,{childList:true,subtree:true});else document.addEventListener('DOMContentLoaded',()=>mgObserver.observe(document.body,{childList:true,subtree:true}));mgEnhanceForm().catch(()=>{});
