const AFILIA_VERSION='0.5.0';
const SUPABASE_URL='https://yjgwlofhordbmjomxcdx.supabase.co';
const SUPABASE_KEY='sb_publishable_qASwZXIwsbouYZpC-X0YWA_675aTqWN';
const FUNCTIONS=SUPABASE_URL+'/functions/v1';
const TELEGRAM='https://t.me/afiliaapp_bot';
const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.afiliaSupabase=supabase;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let currentUser=null;
let integrationState=[];
function toast(text){const el=$('toast');if(!el)return;el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function showModal(html){$('modalBody').innerHTML=html;$('modal').classList.add('show')}
function closeModal(){ $('modal').classList.remove('show') }
window.closeModal=closeModal;
window.openTelegram=()=>window.open(TELEGRAM,'_blank');
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));history.replaceState(null,'','#'+id);if(id==='activity')loadActivity();if(id==='results')loadResults();if(id==='integrations')loadIntegrations()}
window.go=go;
async function session(){const{data:{session}}=await supabase.auth.getSession();if(!session){location.replace('./auth.html');return null}currentUser=session.user;return session}
async function fn(slug,body){const s=await session();if(!s)throw Error('unauthorized');const r=await fetch(`${FUNCTIONS}/${slug}`,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,apikey:SUPABASE_KEY,'content-type':'application/json'},body:JSON.stringify(body)});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Object.assign(Error(j.error||'request_failed'),{payload:j,status:r.status});return j}
async function loadProfile(){if(!currentUser)return;const name=currentUser.user_metadata?.name||currentUser.email?.split('@')[0]||'Usuário';$('helloName').textContent=name.split(' ')[0];$('profileName').textContent=name;$('profileEmail').textContent=currentUser.email||''}
async function openProfile(){if(!currentUser)await session();const name=currentUser?.user_metadata?.name||currentUser?.email||'Conta Afilia';showModal(`<h3>Minha conta</h3><p>${esc(name)}</p><div class="notice good"><strong>Conta ativa</strong><br>${esc(currentUser?.email||'')}</div><div class="notice"><strong>Afilia ${AFILIA_VERSION}</strong><br>Telegram para operação. Painel web para gestão, integrações e resultados.</div><div class="actions"><button class="btn secondary full" onclick="closeModal()">Voltar</button><button class="btn danger full" onclick="logoutAfilia()">Sair da conta</button></div>`)}
async function logoutAfilia(){await supabase.auth.signOut();location.replace('./auth.html?loggedout=1')}
window.openProfile=openProfile;window.logoutAfilia=logoutAfilia;
async function loadOverview(){const uid=currentUser.id;const start=new Date();start.setHours(0,0,0,0);const iso=start.toISOString();const week=new Date(Date.now()-6*864e5);week.setHours(0,0,0,0);
const [a,b,c,d,e,f]=await Promise.all([
 supabase.from('offers').select('*',{count:'exact',head:true}).eq('user_id',uid).gte('created_at',iso),
 supabase.from('offers').select('*',{count:'exact',head:true}).eq('user_id',uid).eq('status','published').gte('created_at',iso),
 supabase.from('queue_items').select('*',{count:'exact',head:true}).eq('user_id',uid).in('status',['pending','processing','ready_to_share']),
 supabase.from('automation_rules').select('*',{count:'exact',head:true}).eq('user_id',uid).eq('is_enabled',true),
 supabase.from('offers').select('status,conversion_status,created_at,metadata').eq('user_id',uid).gte('created_at',week.toISOString()).order('created_at',{ascending:true}),
 supabase.from('telegram_user_links').select('telegram_user_id,username,first_name').eq('user_id',uid).maybeSingle()
]);
$('kpiReceived').textContent=a.count||0;$('kpiPublished').textContent=b.count||0;$('kpiQueue').textContent=c.count||0;$('kpiAutomations').textContent=d.count||0;
const rows=e.data||[];const conv=rows.filter(x=>x.conversion_status==='converted').length;const failed=rows.filter(x=>x.status==='failed'||x.conversion_status==='failed').length;$('weekOffers').textContent=rows.length;$('weekConversion').textContent=rows.length?Math.round(conv/rows.length*100)+'%':'—';$('weekErrors').textContent=failed;
const tg=f.data;$('telegramStatus').textContent=tg?'Conectado':'Conectar';$('telegramStatus').className='chip '+(tg?'green':'orange');$('telegramSub').textContent=tg?`@${tg.username||tg.first_name||'Telegram'} • central operacional`:'Use o Telegram para operar o Afilia';renderWeek(rows)}
function renderWeek(rows){const days=[];for(let i=6;i>=0;i--){const d=new Date(Date.now()-i*864e5),key=d.toISOString().slice(0,10);days.push({key,label:d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),n:0})}for(const r of rows){const k=new Date(r.created_at).toISOString().slice(0,10);const d=days.find(x=>x.key===k);if(d)d.n++}const max=Math.max(1,...days.map(x=>x.n));$('weekChart').innerHTML=days.map(x=>`<div class="barCol"><span>${x.n}</span><i style="height:${Math.max(5,x.n/max*100)}%"></i><small>${x.label}</small></div>`).join('')}
async function loadResults(){const uid=currentUser.id;const since=new Date(Date.now()-30*864e5).toISOString();const{data=[]}=await supabase.from('offers').select('status,conversion_status,created_at,metadata').eq('user_id',uid).gte('created_at',since);const total=data.length,pub=data.filter(x=>x.status==='published').length,conv=data.filter(x=>x.conversion_status==='converted').length,fail=data.filter(x=>x.status==='failed'||x.conversion_status==='failed').length;$('rTotal').textContent=total;$('rPublished').textContent=pub;$('rConverted').textContent=conv;$('rFailed').textContent=fail;const map={};for(const x of data){const k=x.metadata?.marketplace_slug||'outros';map[k]=(map[k]||0)+1}const sum=Math.max(1,total);$('marketBreakdown').innerHTML=Object.keys(map).length?Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([k,n])=>`<div class="metricRow"><div><b>${esc(k)}</b><span>${n} ofertas</span></div><div class="meter"><i style="width:${n/sum*100}%"></i></div></div>`).join(''):'<div class="emptySmall">Os resultados começam a aparecer conforme você usa o bot.</div>'}
async function loadActivity(){const uid=currentUser.id;const{data=[]}=await supabase.from('offers').select('id,status,conversion_status,created_at,source_url,affiliate_url,metadata').eq('user_id',uid).order('created_at',{ascending:false}).limit(30);$('activityList').innerHTML=data.length?data.map(x=>{const mk=x.metadata?.marketplace_slug||'link';const icon=x.status==='failed'?'🔴':x.status==='published'?'🟢':x.conversion_status==='converted'?'🟢':'🟡';return `<div class="activityItem"><div class="activityIcon">${icon}</div><div><b>${esc(mk)}</b><span>${esc(x.status)} • ${esc(x.conversion_status)}</span><small>${new Date(x.created_at).toLocaleString('pt-BR')}</small></div></div>`}).join(''):'<div class="emptySmall">Nenhuma atividade ainda. Envie um link para o bot do Telegram.</div>'}
async function loadIntegrations(){try{const j=await fn('integration-vault',{action:'status',marketplace:'shopee'});integrationState=j.integrations||[]}catch{integrationState=[]}const get=slug=>integrationState.find(x=>x.marketplaces?.slug===slug);for(const slug of ['shopee','amazon','mercadolivre','magalu']){const x=get(slug),el=$('st_'+slug);if(!el)continue;el.textContent=x?.credentials_configured?'Conectado':(slug==='mercadolivre'||slug==='magalu'?'Modo link':'Conectar');el.className='chip '+(x?.credentials_configured?'green':(slug==='mercadolivre'||slug==='magalu'?'':'orange'))}}
async function connectTelegram(){try{const j=await fn('telegram-connect',{});if(j.linked){toast('Telegram já conectado');window.open(TELEGRAM,'_blank')}else if(j.url)location.href=j.url}catch{toast('Não foi possível iniciar a conexão agora')}}
window.connectTelegram=connectTelegram;
function openIntegration(slug){const names={shopee:'Shopee',amazon:'Amazon',mercadolivre:'Mercado Livre',magalu:'Magalu'};if(slug==='mercadolivre'||slug==='magalu'){showModal(`<h3>${names[slug]}</h3><p>Por enquanto o Afilia trabalha com links de afiliado dessa plataforma. Quando a API oficial estiver disponível para esta integração, você poderá ativá-la aqui.</p><div class="notice"><strong>Não informe senha da sua conta.</strong><br>O Afilia nunca precisa da senha do marketplace.</div><button class="btn secondary full" onclick="closeModal()">Entendi</button>`);return}if(slug==='shopee')showModal(`<h3>Conectar Shopee</h3><p>Use somente as credenciais da <b>Affiliate Open API</b>.</p><label>APP ID</label><input class="field" id="intPublic" placeholder="App ID"><label>SECRET</label><input class="field" id="intSecret" type="password" placeholder="Secret"><div class="notice warn"><strong>Nunca coloque sua senha da Shopee aqui.</strong><br>App ID e Secret aparecem na área Open API quando o acesso é liberado.</div><div class="actions"><button class="btn secondary full" onclick="closeModal()">Cancelar</button><button class="btn primary full" onclick="saveIntegration('shopee')">Salvar com segurança</button></div>`);else showModal(`<h3>Conectar Amazon</h3><p>Conecte os dados oficiais da sua integração de afiliados.</p><label>PARTNER TAG</label><input class="field" id="intTag" placeholder="seutag-20"><label>CLIENT ID</label><input class="field" id="intPublic" placeholder="Client ID"><label>CLIENT SECRET</label><input class="field" id="intSecret" type="password" placeholder="Client Secret"><div class="notice good"><strong>Credenciais protegidas.</strong><br>Segredos são enviados ao cofre no backend e não ficam salvos neste navegador.</div><div class="actions"><button class="btn secondary full" onclick="closeModal()">Cancelar</button><button class="btn primary full" onclick="saveIntegration('amazon')">Salvar com segurança</button></div>`)}
window.openIntegration=openIntegration;
async function saveIntegration(slug){try{let body={action:'save',marketplace:slug,publicData:{},secrets:{}};if(slug==='shopee'){body.publicData.appId=$('intPublic').value.trim();body.secrets.appSecret=$('intSecret').value.trim()}else{body.publicData.partnerTag=$('intTag').value.trim();body.publicData.clientId=$('intPublic').value.trim();body.secrets.clientSecret=$('intSecret').value.trim()}if(Object.values(body.publicData).some(x=>!x)||Object.values(body.secrets).some(x=>!x)){toast('Preencha todos os campos');return}await fn('integration-vault',body);closeModal();toast('Credenciais salvas com segurança');await loadIntegrations()}catch(e){toast(e.payload?.error==='missing_credentials'?'Confira os campos':'Não foi possível salvar agora')}}
window.saveIntegration=saveIntegration;
function openWhatsAppIntegration(){showModal(`<h3>WhatsApp</h3><p>Você já pode testar o envio de uma oferta convertida sem entregar sua sessão do WhatsApp ao Afilia.</p><div class="notice good"><strong>✅ Compartilhamento seguro disponível</strong><br>Depois de converter uma oferta no Telegram, toque em <b>Abrir no WhatsApp</b>. O Afilia abre o WhatsApp com a mensagem pronta e você escolhe o grupo ou contato.</div><div class="notice warn"><strong>🪞 Espelhamento automático</strong><br>Essa etapa exige um worker de WhatsApp conectado como dispositivo vinculado. Ainda não está habilitada para evitar prometer automação antes do motor estar pronto.</div><div class="actions"><button class="btn primary full" onclick="window.open('https://wa.me/','_blank')">Abrir WhatsApp</button><button class="btn secondary full" onclick="closeModal()">Fechar</button></div>`)}
window.openWhatsAppIntegration=openWhatsAppIntegration;
function openFiscalHub(){showModal(`<h3>Notas fiscais em massa</h3><p>Importe a planilha de pagamentos/comissões para conferir o lote antes da emissão.</p><label>PLANILHA</label><input id="fiscalFile" class="field" type="file" accept=".xlsx,.xls,.csv"><button class="btn primary full" onclick="readFiscalSheet()">📄 Ler e validar planilha</button><div id="fiscalResult" class="notice" style="display:none"></div><div class="notice good"><strong>🔐 Certificado digital</strong><br>O Afilia não salvará certificado A1 nem senha no navegador. A emissão em massa será habilitada somente após conectarmos um emissor fiscal/cofre compatível.</div><div class="notice warn"><strong>Próxima etapa</strong><br>Mapear as colunas do Excel, validar CPF/CNPJ, valores e competência; depois gerar um lote de emissão com revisão antes de transmitir.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}
window.openFiscalHub=openFiscalHub;
async function readFiscalSheet(){const file=$('fiscalFile')?.files?.[0],out=$('fiscalResult');if(!file){toast('Escolha uma planilha');return}out.style.display='block';out.innerHTML='<strong>Lendo planilha…</strong>';try{const XLSX=await import('https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:''});const headers=rows.length?Object.keys(rows[0]):[];const normalized=headers.map(h=>h.toLowerCase());const looksCpf=normalized.some(h=>h.includes('cpf')||h.includes('cnpj')||h.includes('documento'));const looksValue=normalized.some(h=>h.includes('valor')||h.includes('comiss')||h.includes('total'));out.innerHTML=`<strong>✅ Planilha lida</strong><br>${rows.length} linha(s) encontradas • ${headers.length} coluna(s).<br><br><b>Colunas:</b> ${headers.slice(0,12).map(esc).join(', ')||'nenhuma'}${looksCpf&&looksValue?'<br><br>Os campos principais parecem existir. Próximo passo: mapear e validar o lote.':'<br><br>⚠️ Ainda não identifiquei automaticamente documento e valor. Vamos criar o mapeamento de colunas antes da emissão.'}`;window.afiliaFiscalPreview={fileName:file.name,rowCount:rows.length,headers,rows:rows.slice(0,50)}}catch(e){console.error(e);out.innerHTML='<strong>❌ Não consegui ler essa planilha.</strong><br>Tente um arquivo XLSX, XLS ou CSV válido.'}}
window.readFiscalSheet=readFiscalSheet;
function injectNewModules(){const integrations=$('integrations');if(integrations&&!$('afiliaWhatsappCard')){const tgCard=integrations.querySelector('.card');const card=document.createElement('div');card.id='afiliaWhatsappCard';card.className='card click';card.onclick=openWhatsAppIntegration;card.innerHTML='<div class="int"><div class="intL"><div class="intLogo">📲</div><div><h4>WhatsApp</h4><p>Compartilhamento seguro agora • automação depois</p></div></div><span class="chip green">Testar</span></div>';tgCard?.after(card)}const home=$('home');if(home&&!$('fiscalHubCard')){const section=document.createElement('div');section.id='fiscalHubCard';section.innerHTML='<div class="sectionHead"><h3>Ferramentas</h3><span>gestão</span></div><div class="card click" onclick="openFiscalHub()"><div class="int"><div class="intL"><div class="intLogo">🧾</div><div><h4>Notas fiscais em massa</h4><p>Ler Excel, validar lote e preparar emissão</p></div></div><span class="chip orange">Beta</span></div></div>';home.appendChild(section)}}
async function init(){const s=await session();if(!s)return;currentUser=s.user;injectNewModules();await loadProfile();const hash=location.hash.replace('#','');go(['results','integrations','activity'].includes(hash)?hash:'home');await Promise.allSettled([loadOverview(),loadIntegrations()]);document.querySelector('.profile')?.addEventListener('click',openProfile)}
init();