let mirrorReady=false;
let mirrorRules=[];
let mirrorGroups=[];
let mirrorTemplates=[];
let mirrorDevices=[];
let mirrorEditing=null;
const me=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mdb=()=>window.afiliaSupabase||null;
function mToast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function mModal(html){const body=document.getElementById('modalBody'),modal=document.getElementById('modal');if(!body||!modal)return;body.innerHTML=html;modal.classList.add('show')}
async function mUid(){const db=mdb();if(!db)return null;const{data:{session}}=await db.auth.getSession();return session?.user?.id||null}
function injectMirrorStyles(){if(document.getElementById('afilia-mirror-styles'))return;const s=document.createElement('style');s.id='afilia-mirror-styles';s.textContent=`
.mirrorList{display:grid;gap:9px}.mirrorItem{border:1px solid #29313a;background:#0d1115;border-radius:18px;padding:14px}.mirrorHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.mirrorHead h4{margin:0;font-size:14px}.mirrorMeta{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.mirrorLine{font-size:10px;color:#9aa6b3;line-height:1.45;margin-top:8px}.mirrorActions{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:12px}.mirrorActions button{padding:9px 6px;border-radius:11px;border:1px solid #303943;background:#171d23;color:#d9dfe6;font-size:9px;font-weight:900}.mirrorActions .danger{color:#ff9a9a;border-color:rgba(255,119,119,.25);background:rgba(255,119,119,.07)}.mirrorChecks{display:grid;gap:7px;max-height:240px;overflow:auto;padding:5px 0}.mirrorCheckRow{display:flex;gap:9px;align-items:center;border:1px solid #252e37;background:#0c1115;border-radius:13px;padding:10px}.mirrorCheckRow input{width:18px;height:18px}.mirrorCheckRow span{font-size:10px;line-height:1.3}.mirrorEmpty{padding:26px 10px;text-align:center;color:#87939f;font-size:11px;line-height:1.5}.mirrorDiag{font-size:9px;color:#7e8995;margin-top:5px}`;document.head.appendChild(s)}
function injectMirrorEntry(){if(document.getElementById('mirrorEntry'))return;const screen=document.getElementById('integrations');if(!screen)return;const wrap=document.createElement('div');wrap.id='mirrorEntry';wrap.innerHTML=`<div class="sectionHead"><h3>Automações</h3><span>WhatsApp</span></div><div class="card click" onclick="openMirrorManager()"><div class="int"><div class="intL"><div class="intLogo">🪞</div><div><h4>Espelhamento automático</h4><p>Grupo origem → Mercado Livre → template → grupos destino</p></div></div><span id="mirrorCountChip" class="chip">Configurar</span></div></div>`;const templateEntry=document.getElementById('templateEntry');if(templateEntry)screen.insertBefore(wrap,templateEntry);else screen.appendChild(wrap)}
async function loadMirrorData(){const db=mdb(),uid=await mUid();if(!db||!uid)return;const [r,g,t,d]=await Promise.all([
 db.from('mirror_rules').select('id,name,source_connection_id,source_group_ref_id,template_id,browser_device_id,marketplaces,is_active,created_at,updated_at').eq('user_id',uid).order('updated_at',{ascending:false}),
 db.from('whatsapp_group_refs').select('id,connection_id,display_name,role,is_enabled,name_status').eq('user_id',uid).eq('name_status','verified').order('display_name',{ascending:true}),
 db.from('templates').select('id,name,is_default,is_active,marketplace_id').eq('user_id',uid).eq('marketplace_id',3).eq('is_active',true).order('is_default',{ascending:false}),
 db.from('browser_bridge_devices').select('id,device_name,status,last_seen_at,marketplace_slug').eq('user_id',uid).eq('marketplace_slug','mercado-livre').order('last_seen_at',{ascending:false})
 ]);if(r.error)console.error(r.error);if(g.error)console.error(g.error);if(t.error)console.error(t.error);if(d.error)console.error(d.error);mirrorRules=r.data||[];mirrorGroups=g.data||[];mirrorTemplates=t.data||[];mirrorDevices=d.data||[];for(const rule of mirrorRules){const q=await db.from('mirror_rule_targets').select('group_ref_id,is_active').eq('mirror_rule_id',rule.id).eq('user_id',uid);rule.targets=(q.data||[]).filter(x=>x.is_active).map(x=>x.group_ref_id)}const chip=document.getElementById('mirrorCountChip');if(chip){const active=mirrorRules.filter(x=>x.is_active).length;chip.textContent=mirrorRules.length?`${active}/${mirrorRules.length} ativa${mirrorRules.length===1?'':'s'}`:'Configurar';chip.className='chip '+(active?'green':'')}}
function mGroup(id){return mirrorGroups.find(x=>x.id===id)}
function mTemplate(id){return mirrorTemplates.find(x=>x.id===id)}
function mDevice(id){return mirrorDevices.find(x=>x.id===id)}
function mirrorListHtml(){if(!mirrorRules.length)return `<div class="mirrorEmpty">Nenhum espelhamento criado ainda.<br>Crie uma regra para transformar ofertas do grupo origem e publicar nos seus grupos automaticamente.</div>`;return `<div class="mirrorList">${mirrorRules.map(r=>{const src=mGroup(r.source_group_ref_id),tpl=mTemplate(r.template_id),dev=mDevice(r.browser_device_id);return `<div class="mirrorItem"><div class="mirrorHead"><div><h4>${me(r.name)}</h4><div class="mirrorMeta"><span class="chip">Mercado Livre</span><span class="chip ${r.is_active?'green':'orange'}">${r.is_active?'Ativa':'Pausada'}</span></div></div></div><div class="mirrorLine"><b>Origem:</b> ${me(src?.display_name||'Grupo indisponível')}<br><b>Destinos:</b> ${(r.targets||[]).length}<br><b>Template:</b> ${me(tpl?.name||'Padrão Mercado Livre')}<br><b>Extensão:</b> ${me(dev?.device_name||'Automática')}</div><div class="mirrorActions"><button onclick="editMirrorRule('${r.id}')">Editar</button><button onclick="toggleMirrorRule('${r.id}')">${r.is_active?'Pausar':'Ativar'}</button><button class="danger" onclick="deleteMirrorRule('${r.id}')">Excluir</button></div></div>`}).join('')}</div>`}
async function openMirrorManager(){await loadMirrorData();mModal(`<h3>Espelhamento automático</h3><p>Quando chegar um link do Mercado Livre no grupo origem, o Afilia converte pela sua extensão, aplica o template e publica nos destinos.</p><div class="notice good"><strong>Fluxo automático</strong><br>Origem → identificar link → gerar seu meli.la → título/preço/foto → template → WhatsApp.</div><button class="btn primary full" onclick="newMirrorRule()">+ Nova regra</button><div style="height:10px"></div><div id="mirrorListHost">${mirrorListHtml()}</div><div class="notice"><strong>Importante:</strong><br>A extensão do Mercado Livre precisa estar conectada para converter links novos. Se ela estiver offline, o job fica aguardando até voltar.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}
window.openMirrorManager=openMirrorManager;
function newestDevice(){const cutoff=Date.now()-20*60*1000;return mirrorDevices.find(x=>x.status==='online'&&x.last_seen_at&&new Date(x.last_seen_at).getTime()>cutoff)||mirrorDevices[0]||null}
async function mirrorForm(row=null){await loadMirrorData();mirrorEditing=row?.id||null;const targets=new Set(row?.targets||[]);const src=row?.source_group_ref_id||'';const dev=row?.browser_device_id||newestDevice()?.id||'';const tpl=row?.template_id||'';mModal(`<h3>${row?'Editar':'Novo'} espelhamento</h3><p>Escolha exatamente de onde a oferta vem e para onde ela deve ir.</p><label>NOME DA REGRA</label><input id="mirName" class="field" maxlength="80" placeholder="Ex.: Mercado Livre → meus grupos" value="${me(row?.name||'')}"><label>GRUPO ORIGEM</label><select id="mirSource" class="field" onchange="renderMirrorTargets()"><option value="">Selecione o grupo origem</option>${mirrorGroups.map(g=>`<option value="${g.id}" ${src===g.id?'selected':''}>${me(g.display_name||'Grupo')}</option>`).join('')}</select><label>EXTENSÃO MERCADO LIVRE</label><select id="mirDevice" class="field"><option value="">Escolher automaticamente a mais recente</option>${mirrorDevices.map(d=>`<option value="${d.id}" ${dev===d.id?'selected':''}>${me(d.device_name)}${d.status==='online'?' • online':''}</option>`).join('')}</select><div class="mirrorDiag">Para evitar navegador errado, prefira selecionar o Device ID que usa sua conta de afiliado.</div><label>TEMPLATE</label><select id="mirTemplate" class="field"><option value="">Template padrão do Mercado Livre</option>${mirrorTemplates.map(t=>`<option value="${t.id}" ${tpl===t.id?'selected':''}>${me(t.name)}${t.is_default?' • padrão':''}</option>`).join('')}</select><label>GRUPOS DESTINO</label><div id="mirTargets" class="mirrorChecks"></div><label class="templateCheck"><input id="mirActive" type="checkbox" ${row?.is_active===false?'':'checked'}> Regra ativa</label><div class="notice warn"><strong>Segurança:</strong><br>O grupo origem nunca é usado como destino na mesma regra. Destinos selecionados serão habilitados para envio automático.</div><div class="actions"><button class="btn secondary full" onclick="openMirrorManager()">Cancelar</button><button class="btn primary full" onclick="saveMirrorRule()">Salvar regra</button></div>`);window._mirrorTargetSeed=targets;renderMirrorTargets()}
function newMirrorRule(){mirrorForm(null)}window.newMirrorRule=newMirrorRule;
function editMirrorRule(id){const r=mirrorRules.find(x=>x.id===id);if(r)mirrorForm(r)}window.editMirrorRule=editMirrorRule;
function renderMirrorTargets(){const host=document.getElementById('mirTargets');if(!host)return;const src=document.getElementById('mirSource')?.value||'';const seed=window._mirrorTargetSeed||new Set();const rows=mirrorGroups.filter(g=>g.id!==src);host.innerHTML=rows.length?rows.map(g=>`<label class="mirrorCheckRow"><input type="checkbox" class="mirTarget" value="${g.id}" ${seed.has(g.id)?'checked':''}><span>${me(g.display_name||'Grupo')}${g.is_enabled?'':'<br><small style="color:#ffb476">será habilitado ao salvar</small>'}</span></label>`).join(''):'<div class="mirrorEmpty">Nenhum outro grupo verificado disponível.</div>'}
window.renderMirrorTargets=renderMirrorTargets;
async function saveMirrorRule(){const db=mdb(),uid=await mUid();if(!db||!uid)return;const name=document.getElementById('mirName')?.value.trim();const sourceId=document.getElementById('mirSource')?.value||'';const deviceId=document.getElementById('mirDevice')?.value||null;const templateId=document.getElementById('mirTemplate')?.value||null;const isActive=!!document.getElementById('mirActive')?.checked;const targetIds=[...document.querySelectorAll('.mirTarget:checked')].map(x=>x.value);const source=mGroup(sourceId);if(!name||!sourceId||!source){mToast('Escolha um nome e o grupo origem');return}if(!targetIds.length){mToast('Escolha pelo menos um grupo destino');return}if(targetIds.includes(sourceId)){mToast('O grupo origem não pode ser destino');return}try{const payload={user_id:uid,name,source_connection_id:source.connection_id,source_group_ref_id:sourceId,template_id:templateId,browser_device_id:deviceId,marketplaces:['mercado-livre'],is_active:isActive,updated_at:new Date().toISOString()};let ruleId=mirrorEditing;if(ruleId){const{error}=await db.from('mirror_rules').update(payload).eq('id',ruleId).eq('user_id',uid);if(error)throw error;const del=await db.from('mirror_rule_targets').delete().eq('mirror_rule_id',ruleId).eq('user_id',uid);if(del.error)throw del.error}else{const{data,error}=await db.from('mirror_rules').insert(payload).select('id').single();if(error)throw error;ruleId=data.id}const targets=targetIds.map(id=>({user_id:uid,mirror_rule_id:ruleId,group_ref_id:id,is_active:true}));const ins=await db.from('mirror_rule_targets').insert(targets);if(ins.error)throw ins.error;const en=await db.from('whatsapp_group_refs').update({is_enabled:true,updated_at:new Date().toISOString()}).eq('user_id',uid).in('id',targetIds);if(en.error)console.warn(en.error);mirrorEditing=null;window._mirrorTargetSeed=null;mToast('Espelhamento salvo');await openMirrorManager()}catch(e){console.error(e);mToast('Não foi possível salvar o espelhamento')}}
window.saveMirrorRule=saveMirrorRule;
async function toggleMirrorRule(id){const db=mdb(),uid=await mUid(),r=mirrorRules.find(x=>x.id===id);if(!db||!uid||!r)return;const{error}=await db.from('mirror_rules').update({is_active:!r.is_active,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',uid);if(error){mToast('Não foi possível alterar');return}mToast(r.is_active?'Espelhamento pausado':'Espelhamento ativado');await openMirrorManager()}
window.toggleMirrorRule=toggleMirrorRule;
async function deleteMirrorRule(id){const r=mirrorRules.find(x=>x.id===id);if(!r||!confirm(`Excluir “${r.name}”?`))return;const db=mdb(),uid=await mUid();const{error}=await db.from('mirror_rules').delete().eq('id',id).eq('user_id',uid);if(error){mToast('Não foi possível excluir');return}mToast('Espelhamento excluído');await openMirrorManager()}
window.deleteMirrorRule=deleteMirrorRule;
async function bootMirror(){if(mirrorReady)return;let tries=0;while(!mdb()&&tries++<50)await new Promise(r=>setTimeout(r,120));if(!mdb())return;mirrorReady=true;injectMirrorStyles();let waits=0;while(!document.getElementById('integrations')&&waits++<30)await new Promise(r=>setTimeout(r,100));injectMirrorEntry();await loadMirrorData()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootMirror);else bootMirror();
