let offerModeReady=false;
const omEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const omDb=()=>window.afiliaSupabase||null;
async function omUid(){const db=omDb();if(!db)return null;const{data:{session}}=await db.auth.getSession();return session?.user?.id||null}
function omToast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function injectOfferModeStyles(){if(document.getElementById('afilia-offer-mode-styles'))return;const s=document.createElement('style');s.id='afilia-offer-mode-styles';s.textContent=`
.offerModeCard{border:1px solid #29313a;background:#10161b;border-radius:20px;padding:14px;margin-top:10px}.offerModeHead{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.offerModeHead h4{margin:0;font-size:14px}.offerModeHead p{margin:5px 0 0;color:#8e9aa7;font-size:10px;line-height:1.45}.offerModeChoices{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:13px}.offerModeChoice{border:1px solid #303944;background:#171d23;color:#d8dfe6;border-radius:15px;padding:12px;text-align:left;cursor:pointer}.offerModeChoice strong{display:block;font-size:11px}.offerModeChoice span{display:block;color:#8e9aa7;font-size:9px;line-height:1.4;margin-top:5px}.offerModeChoice.active{border-color:#d4ff32;background:rgba(212,255,50,.09);box-shadow:inset 0 0 0 1px rgba(212,255,50,.18)}.offerModeChoice.active strong{color:#d4ff32}.offerModeNote{margin-top:10px;color:#82909d;font-size:9px;line-height:1.45}.offerModeNote b{color:#c9d2db}`;document.head.appendChild(s)}
async function readOfferMode(){const db=omDb(),uid=await omUid();if(!db||!uid)return'post';const{data,error}=await db.from('profiles').select('telegram_offer_mode').eq('user_id',uid).maybeSingle();if(error){console.error(error);return'post'}return data?.telegram_offer_mode==='copy'?'copy':'post'}
async function setOfferMode(mode){if(!['post','copy'].includes(mode))return;const db=omDb(),uid=await omUid();if(!db||!uid)return;const{error}=await db.from('profiles').update({telegram_offer_mode:mode,updated_at:new Date().toISOString()}).eq('user_id',uid);if(error){console.error(error);omToast('Não foi possível alterar o modo');return}await renderOfferMode();omToast(mode==='post'?'Modo POST: links serão preservados':'Modo COPY: links comuns serão convertidos')}
window.setOfferMode=setOfferMode;
async function renderOfferMode(){const mode=await readOfferMode(),host=document.getElementById('offerModeHost');if(!host)return;host.innerHTML=`<div class="offerModeCard"><div class="offerModeHead"><div><h4>Modo dos links</h4><p>Escolha como o bot deve tratar os links enviados no Telegram.</p></div><span class="chip ${mode==='copy'?'orange':'green'}">${mode.toUpperCase()}</span></div><div class="offerModeChoices"><button class="offerModeChoice ${mode==='post'?'active':''}" onclick="setOfferMode('post')"><strong>📝 POST</strong><span>Já tenho link de afiliado. O Afilia preserva exatamente o link e só monta a oferta.</span></button><button class="offerModeChoice ${mode==='copy'?'active':''}" onclick="setOfferMode('copy')"><strong>🔄 COPY</strong><span>Tenho link comum do produto. O Afilia converte usando a API da minha conta.</span></button></div><div class="offerModeNote"><b>Importante:</b> ter API configurada não muda este modo automaticamente. Você escolhe e o Afilia respeita até trocar novamente.</div></div>`}
function injectOfferModeEntry(){if(document.getElementById('offerModeHost'))return;const screen=document.getElementById('integrations');if(!screen)return;const host=document.createElement('div');host.id='offerModeHost';const tpl=document.getElementById('templateEntry');if(tpl?.parentNode)tpl.parentNode.insertBefore(host,tpl.nextSibling);else{const notice=[...screen.querySelectorAll('.notice')].find(x=>x.textContent.includes('Segurança:'));if(notice)screen.insertBefore(host,notice);else screen.appendChild(host)}}
async function bootOfferMode(){if(offerModeReady)return;let tries=0;while(!omDb()&&tries++<40)await new Promise(r=>setTimeout(r,150));if(!omDb())return;offerModeReady=true;injectOfferModeStyles();injectOfferModeEntry();await renderOfferMode()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootOfferMode);else bootOfferMode();
