const TEMPLATE_MARKETS=[{id:1,name:'Shopee',slug:'shopee',icon:'S'},{id:2,name:'Amazon',slug:'amazon',icon:'a'},{id:3,name:'Mercado Livre',slug:'mercado-livre',icon:'ML'},{id:4,name:'Magalu',slug:'magalu',icon:'M'}];
const TEMPLATE_VARS=['{titulo}','{preco}','{preco_original}','{desconto}','{cupom}','{link}','{marketplace}'];
let templateRows=[];
let templateFilter='all';
let templateEditing=null;
let templateReady=false;
const te=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tdb(){return window.afiliaSupabase||null}
function tModal(html){const body=document.getElementById('modalBody'),modal=document.getElementById('modal');if(!body||!modal)return;body.innerHTML=html;modal.classList.add('show')}
function tClose(){document.getElementById('modal')?.classList.remove('show')}
function tToast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
function marketById(id){return TEMPLATE_MARKETS.find(x=>x.id===Number(id))}
function injectTemplateStyles(){if(document.getElementById('afilia-template-styles'))return;const s=document.createElement('style');s.id='afilia-template-styles';s.textContent=`
.templateTop{display:flex;gap:9px;margin-bottom:13px}.templateTop select{flex:1}.templateList{display:grid;gap:9px}.templateItem{border:1px solid #29313a;background:#0d1115;border-radius:18px;padding:14px}.templateItemHead{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.templateItem h4{margin:0;font-size:14px}.templateMeta{display:flex;gap:6px;flex-wrap:wrap;margin-top:6px}.templatePreview{margin-top:10px;color:#9aa6b3;font-size:10px;line-height:1.45;white-space:pre-wrap;max-height:72px;overflow:hidden}.templateActions{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:12px}.templateActions button{padding:9px 6px;border-radius:11px;border:1px solid #303943;background:#171d23;color:#d9dfe6;font-size:9px;font-weight:900}.templateActions button.primaryMini{background:#d4ff32;color:#0b0e06;border-color:#d4ff32}.templateActions button.dangerMini{color:#ff9a9a;border-color:rgba(255,119,119,.25);background:rgba(255,119,119,.07)}.templateVars{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.templateVars button{border:1px solid #303943;background:#161c22;color:#c8d0d9;border-radius:999px;padding:7px 9px;font-size:9px;font-weight:850}.templateTextarea{min-height:190px;resize:vertical;line-height:1.45}.templateHint{color:#7f8b98;font-size:9px;line-height:1.45;margin-top:8px}.templateCheck{display:flex;align-items:center;gap:9px;margin-top:14px;color:#d6dde5;font-size:11px}.templateCheck input{width:18px;height:18px}.templateEmpty{padding:28px 12px;text-align:center;color:#84909d;font-size:11px;line-height:1.55}`;document.head.appendChild(s)}
function injectTemplateEntry(){if(document.getElementById('templateEntry'))return;const screen=document.getElementById('integrations');if(!screen)return;const notice=[...screen.querySelectorAll('.notice')].find(x=>x.textContent.includes('Segurança:'));const wrap=document.createElement('div');wrap.id='templateEntry';wrap.innerHTML=`<div class="sectionHead"><h3>Mensagens</h3><span>personalização</span></div><div class="card click" onclick="openTemplatesManager()"><div class="int"><div class="intL"><div class="intLogo">✎</div><div><h4>Templates de oferta</h4><p>Crie quantos quiser, separados por marketplace</p></div></div><span id="templateCountChip" class="chip">Gerenciar</span></div></div>`;if(notice)screen.insertBefore(wrap,notice);else screen.appendChild(wrap)}
async function currentUid(){const db=tdb();if(!db)return null;const{data:{session}}=await db.auth.getSession();return session?.user?.id||null}
async function loadTemplateRows(){const db=tdb(),uid=await currentUid();if(!db||!uid)return[];const{data,error}=await db.from('templates').select('id,name,marketplace_id,body,is_default,is_active,created_at,updated_at').eq('user_id',uid).order('updated_at',{ascending:false});if(error){console.error(error);tToast('Não consegui carregar os templates');return[]}templateRows=data||[];const chip=document.getElementById('templateCountChip');if(chip){chip.textContent=templateRows.length?`${templateRows.length} template${templateRows.length===1?'':'s'}`:'Criar';chip.className='chip '+(templateRows.length?'green':'')}return templateRows}
function filteredTemplates(){return templateFilter==='all'?templateRows:templateRows.filter(x=>String(x.marketplace_id)===String(templateFilter))}
function templateListHtml(){const rows=filteredTemplates();if(!rows.length)return `<div class="templateEmpty">Nenhum template${templateFilter==='all'?' ainda':' para este marketplace'}.<br>Crie o primeiro e ele poderá ser usado pelo bot nas ofertas.</div>`;return `<div class="templateList">${rows.map(r=>{const m=marketById(r.marketplace_id);return `<div class="templateItem"><div class="templateItemHead"><div><h4>${te(r.name)}</h4><div class="templateMeta"><span class="chip">${te(m?.name||'Geral')}</span>${r.is_default?'<span class="chip green">Padrão</span>':''}${!r.is_active?'<span class="chip orange">Inativo</span>':''}</div></div></div><div class="templatePreview">${te(r.body)}</div><div class="templateActions"><button onclick="editTemplate('${r.id}')">Editar</button><button onclick="duplicateTemplate('${r.id}')">Duplicar</button><button class="${r.is_default?'':'primaryMini'}" onclick="setDefaultTemplate('${r.id}')">${r.is_default?'Padrão ✓':'Definir padrão'}</button><button onclick="toggleTemplate('${r.id}')">${r.is_active?'Desativar':'Ativar'}</button><button class="dangerMini" onclick="deleteTemplate('${r.id}')">Excluir</button></div></div>`}).join('')}</div>`}
async function openTemplatesManager(){await loadTemplateRows();tModal(`<h3>Templates de oferta</h3><p>Crie mensagens diferentes para cada marketplace. Você pode ter quantos templates quiser e escolher um padrão por marketplace.</p><div class="templateTop"><select id="templateFilter" class="field" onchange="changeTemplateFilter(this.value)"><option value="all">Todos os marketplaces</option>${TEMPLATE_MARKETS.map(m=>`<option value="${m.id}" ${String(templateFilter)===String(m.id)?'selected':''}>${m.name}</option>`).join('')}</select><button class="btn primary" onclick="newTemplate()">+ Novo</button></div><div id="templateListHost">${templateListHtml()}</div><div class="notice"><strong>Variáveis disponíveis:</strong><br>${TEMPLATE_VARS.map(te).join(' • ')}</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}
window.openTemplatesManager=openTemplatesManager;
function changeTemplateFilter(v){templateFilter=v;const host=document.getElementById('templateListHost');if(host)host.innerHTML=templateListHtml()}
window.changeTemplateFilter=changeTemplateFilter;
function templateForm(row=null){templateEditing=row?.id||null;const market=row?.marketplace_id||Number(templateFilter!=='all'?templateFilter:1);tModal(`<h3>${row?'Editar template':'Novo template'}</h3><p>Monte exatamente a mensagem que você quer receber e compartilhar depois da conversão.</p><label>NOME DO TEMPLATE</label><input id="tplName" class="field" maxlength="80" placeholder="Ex.: Oferta Shopee padrão" value="${te(row?.name||'')}"><label>MARKETPLACE</label><select id="tplMarket" class="field">${TEMPLATE_MARKETS.map(m=>`<option value="${m.id}" ${Number(market)===m.id?'selected':''}>${m.name}</option>`).join('')}</select><label>MENSAGEM</label><textarea id="tplBody" class="field templateTextarea" maxlength="4000" placeholder="🔥 {titulo}\n\n💰 Por {preco}\n🔗 {link}">${te(row?.body||'🔥 {titulo}\n\n💰 {preco}\n🔗 {link}')}</textarea><div class="templateVars">${TEMPLATE_VARS.map(v=>`<button type="button" onclick="insertTemplateVar('${v}')">${te(v)}</button>`).join('')}</div><div class="templateHint">As variáveis são substituídas automaticamente quando houver informação disponível. Você pode escrever qualquer texto, emoji ou quebra de linha ao redor delas.</div><label class="templateCheck"><input id="tplDefault" type="checkbox" ${row?.is_default?'checked':''}> Usar como padrão deste marketplace</label><label class="templateCheck"><input id="tplActive" type="checkbox" ${row?.is_active===false?'':'checked'}> Template ativo</label><div class="actions"><button class="btn secondary full" onclick="openTemplatesManager()">Cancelar</button><button class="btn primary full" onclick="saveTemplate()">Salvar template</button></div>`)}
function newTemplate(){templateForm(null)}window.newTemplate=newTemplate;
function editTemplate(id){const r=templateRows.find(x=>x.id===id);if(r)templateForm(r)}window.editTemplate=editTemplate;
function insertTemplateVar(v){const ta=document.getElementById('tplBody');if(!ta)return;const a=ta.selectionStart??ta.value.length,b=ta.selectionEnd??a;ta.value=ta.value.slice(0,a)+v+ta.value.slice(b);ta.focus();ta.selectionStart=ta.selectionEnd=a+v.length}window.insertTemplateVar=insertTemplateVar;
async function saveTemplate(){const db=tdb(),uid=await currentUid();if(!db||!uid)return;const name=document.getElementById('tplName')?.value.trim(),body=document.getElementById('tplBody')?.value.trim(),marketplace_id=Number(document.getElementById('tplMarket')?.value),is_default=!!document.getElementById('tplDefault')?.checked,is_active=!!document.getElementById('tplActive')?.checked;if(!name||!body||!marketplace_id){tToast('Preencha nome, marketplace e mensagem');return}try{if(is_default){await db.from('templates').update({is_default:false,updated_at:new Date().toISOString()}).eq('user_id',uid).eq('marketplace_id',marketplace_id)}const payload={user_id:uid,name,body,marketplace_id,is_default,is_active,updated_at:new Date().toISOString()};let error;if(templateEditing)({error}=await db.from('templates').update(payload).eq('id',templateEditing).eq('user_id',uid));else({error}=await db.from('templates').insert(payload));if(error)throw error;tToast('Template salvo');templateFilter=String(marketplace_id);templateEditing=null;await openTemplatesManager()}catch(e){console.error(e);tToast('Não foi possível salvar o template')}}window.saveTemplate=saveTemplate;
async function setDefaultTemplate(id){const db=tdb(),uid=await currentUid(),row=templateRows.find(x=>x.id===id);if(!db||!uid||!row)return;await db.from('templates').update({is_default:false,updated_at:new Date().toISOString()}).eq('user_id',uid).eq('marketplace_id',row.marketplace_id);const{error}=await db.from('templates').update({is_default:true,is_active:true,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',uid);if(error){tToast('Não foi possível alterar o padrão');return}tToast('Template padrão atualizado');await openTemplatesManager()}window.setDefaultTemplate=setDefaultTemplate;
async function toggleTemplate(id){const db=tdb(),uid=await currentUid(),row=templateRows.find(x=>x.id===id);if(!db||!uid||!row)return;const{error}=await db.from('templates').update({is_active:!row.is_active,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',uid);if(error){tToast('Não foi possível alterar');return}await openTemplatesManager()}window.toggleTemplate=toggleTemplate;
async function duplicateTemplate(id){const db=tdb(),uid=await currentUid(),row=templateRows.find(x=>x.id===id);if(!db||!uid||!row)return;const{error}=await db.from('templates').insert({user_id:uid,name:`${row.name} - cópia`,marketplace_id:row.marketplace_id,body:row.body,is_default:false,is_active:true});if(error){tToast('Não foi possível duplicar');return}tToast('Template duplicado');await openTemplatesManager()}window.duplicateTemplate=duplicateTemplate;
async function deleteTemplate(id){const row=templateRows.find(x=>x.id===id);if(!row)return;if(!confirm(`Excluir o template “${row.name}”?`))return;const db=tdb(),uid=await currentUid();const{error}=await db.from('templates').delete().eq('id',id).eq('user_id',uid);if(error){tToast('Não foi possível excluir');return}tToast('Template excluído');await openTemplatesManager()}window.deleteTemplate=deleteTemplate;
async function bootTemplates(){if(templateReady)return;let tries=0;while(!tdb()&&tries++<40)await new Promise(r=>setTimeout(r,150));if(!tdb())return;templateReady=true;injectTemplateStyles();injectTemplateEntry();await loadTemplateRows()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootTemplates);else bootTemplates();
