const supabase=window.afiliaSupabase;
const escWa=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function modal(html){document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.add('show')}
async function me(){const{data:{session}}=await supabase.auth.getSession();return session?.user||null}
async function waState(){const u=await me();if(!u)return null;const{data:connections=[]}=await supabase.from('whatsapp_connections').select('*').eq('user_id',u.id).order('created_at',{ascending:false});const c=connections[0]||null;let groups=[];if(c){const r=await supabase.from('whatsapp_group_refs').select('*').eq('user_id',u.id).eq('connection_id',c.id).order('display_name');groups=r.data||[]}return{u,c,groups}}
async function injectCard(){const section=document.getElementById('integrations');if(!section||document.getElementById('afiliaWhatsCard'))return;const wrap=document.createElement('div');wrap.id='afiliaWhatsCard';wrap.innerHTML=`<div class="sectionHead"><h3>Distribuição</h3><span>WhatsApp</span></div><div class="card click" onclick="openWhatsAppManager()"><div class="int"><div class="intL"><div class="intLogo">W</div><div><h4>WhatsApp automático</h4><p id="waCardSub">Vincule seu WhatsApp e escolha grupos no Telegram</p></div></div><span id="waCardStatus" class="chip orange">Configurar</span></div></div>`;section.appendChild(wrap);await refreshWaCard()}
async function refreshWaCard(){const s=await waState(),chip=document.getElementById('waCardStatus'),sub=document.getElementById('waCardSub');if(!chip||!sub)return;if(s?.c?.status==='connected'){chip.textContent='Conectado';chip.className='chip green';sub.textContent=`${s.groups.filter(g=>g.is_enabled).length} grupo(s) habilitado(s)`}else if(s?.c){chip.textContent='Aguardando';chip.className='chip orange';sub.textContent='Conexão criada • finalize pelo QR'}else{chip.textContent='Configurar';chip.className='chip orange';sub.textContent='Vincule seu WhatsApp e escolha grupos no Telegram'}}
async function openWhatsAppManager(){const s=await waState();if(!s)return;const c=s.c;if(!c){modal(`<h3>WhatsApp automático</h3><p>Conecte seu WhatsApp como um dispositivo vinculado. Depois o Afilia sincroniza seus grupos e o Telegram passa a mostrar botões de envio direto.</p><div class="notice warn"><strong>Modo avançado</strong><br>Esta conexão mantém uma sessão do WhatsApp Web em um gateway dedicado. O modo manual atual continua disponível como alternativa.</div><button class="btn primary full" onclick="startWhatsAppPairing()">📱 Gerar conexão por QR</button><button class="btn secondary full" onclick="closeModal()">Cancelar</button>`);return}const groups=s.groups;const rows=groups.length?groups.map(g=>`<div class="card"><div class="int"><div><h4>${escWa(g.display_name)}</h4><p>${g.is_enabled?'Aparece como botão no Telegram':'Oculto no Telegram'}</p></div><button class="chip ${g.is_enabled?'green':''}" onclick="toggleWhatsGroup('${g.id}',${!g.is_enabled})">${g.is_enabled?'Ativo':'Inativo'}</button></div></div>`).join(''):'<div class="emptySmall">Os grupos aparecerão aqui quando o gateway terminar de sincronizar o WhatsApp.</div>';modal(`<h3>WhatsApp automático</h3><p>Status: <b>${escWa(c.status)}</b>${c.phone_masked?` • ${escWa(c.phone_masked)}`:''}</p><div class="notice ${c.status==='connected'?'good':'warn'}"><strong>${c.status==='connected'?'✅ Sessão conectada':'⏳ Aguardando conexão'}</strong><br>${c.status==='connected'?'Escolha quais grupos ficarão disponíveis como botões no Telegram.':'Se o QR ainda não apareceu, inicie uma nova vinculação.'}</div>${rows}<div class="actions"><button class="btn primary full" onclick="startWhatsAppPairing()">${c.status==='connected'?'🔄 Reconectar':'📱 Mostrar QR'}</button><button class="btn danger full" onclick="disconnectWhatsApp()">Desvincular</button></div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}
window.openWhatsAppManager=openWhatsAppManager;
async function startWhatsAppPairing(){const u=await me();if(!u)return;let{data:c}=await supabase.from('whatsapp_connections').select('*').eq('user_id',u.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!c){const r=await supabase.from('whatsapp_connections').insert({user_id:u.id,label:'WhatsApp principal',status:'pairing',pairing_method:'qr'}).select('*').single();if(r.error){alert('Não foi possível iniciar a conexão.');return}c=r.data}else await supabase.from('whatsapp_connections').update({status:'pairing',pairing_method:'qr',updated_at:new Date().toISOString()}).eq('id',c.id).eq('user_id',u.id);const pr=await supabase.from('whatsapp_pairing_requests').insert({user_id:u.id,connection_id:c.id,status:'waiting_gateway'}).select('*').single();if(pr.error){alert('Não foi possível solicitar o QR.');return}modal(`<h3>Vincular WhatsApp</h3><p>Abra no WhatsApp: <b>Configurações → Dispositivos conectados → Conectar dispositivo</b>.</p><div id="waQrBox" class="notice"><strong>Preparando QR…</strong><br>O gateway está aguardando a sessão.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`);pollPairing(pr.data.id)}
window.startWhatsAppPairing=startWhatsAppPairing;
async function pollPairing(id){for(let i=0;i<80;i++){await sleep(1500);const{data:p}=await supabase.from('whatsapp_pairing_requests').select('*').eq('id',id).maybeSingle();const box=document.getElementById('waQrBox');if(!box||!p)return;if(p.status==='qr_ready'&&p.qr_payload){box.innerHTML=`<strong>Escaneie este QR no WhatsApp</strong><div id="waQrCanvas" style="background:white;padding:12px;margin:12px auto;width:max-content;border-radius:16px"></div><small>O QR expira rapidamente. Se necessário, gere outro.</small>`;try{const QR=await import('https://esm.sh/qrcode@1.5.4');const canvas=document.createElement('canvas');document.getElementById('waQrCanvas').appendChild(canvas);await QR.toCanvas(canvas,p.qr_payload,{width:230,margin:1})}catch{document.getElementById('waQrCanvas').textContent=p.qr_payload}return}if(p.status==='connected'){box.className='notice good';box.innerHTML='<strong>✅ WhatsApp conectado.</strong><br>Seus grupos serão sincronizados em instantes.';await refreshWaCard();return}if(['expired','failed'].includes(p.status)){box.className='notice warn';box.innerHTML='<strong>Não foi possível concluir.</strong><br>Gere uma nova conexão e tente novamente.';return}}}
async function toggleWhatsGroup(id,on){const u=await me();if(!u)return;await supabase.from('whatsapp_group_refs').update({is_enabled:on,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',u.id);await openWhatsAppManager();await refreshWaCard()}
window.toggleWhatsGroup=toggleWhatsGroup;
async function disconnectWhatsApp(){const u=await me();if(!u||!confirm('Desvincular este WhatsApp do Afilia?'))return;const s=await waState();if(s?.c)await supabase.from('whatsapp_connections').update({status:'disconnected',updated_at:new Date().toISOString()}).eq('id',s.c.id).eq('user_id',u.id);closeModal();await refreshWaCard()}
window.disconnectWhatsApp=disconnectWhatsApp;
setTimeout(injectCard,900);window.addEventListener('hashchange',()=>setTimeout(injectCard,200));