const db=()=>window.afiliaSupabase;
const escWa=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const waAutoWaitTried=new Set();
function modal(html){const body=document.getElementById('modalBody'),root=document.getElementById('modal');if(!body||!root){console.error('Afilia modal not found');return}body.innerHTML=html;root.classList.add('show')}
async function me(){const supabase=db();if(!supabase)return null;const{data:{session}}=await supabase.auth.getSession();return session?.user||null}
async function edgeErrorDetail(error,fallback){try{const ctx=error?.context;if(ctx&&typeof ctx.clone==='function'){const body=await ctx.clone().json();return body?.detail||body?.reason||body?.error||fallback}}catch{}return error?.message||fallback}
async function waState(){const u=await me(),supabase=db();if(!u||!supabase)return null;const{data:connections=[]}=await supabase.from('whatsapp_connections').select('*').eq('user_id',u.id).order('created_at',{ascending:false});const c=connections[0]||null;let groups=[];if(c){const r=await supabase.from('whatsapp_group_refs').select('*').eq('user_id',u.id).eq('connection_id',c.id).order('display_name');groups=r.data||[]}return{u,c,groups}}
async function injectCard(){const section=document.getElementById('integrations');if(!section||document.getElementById('afiliaWhatsCard'))return;const wrap=document.createElement('div');wrap.id='afiliaWhatsCard';wrap.innerHTML=`<div class="sectionHead"><h3>Distribuição</h3><span>WhatsApp</span></div><div class="card click" onclick="openWhatsAppManager()"><div class="int"><div class="intL"><div class="intLogo">W</div><div><h4>WhatsApp automático</h4><p id="waCardSub">Vincule seu WhatsApp e escolha grupos no Telegram</p></div></div><span id="waCardStatus" class="chip orange">Configurar</span></div></div>`;section.appendChild(wrap);await refreshWaCard()}
async function refreshWaCard(){const s=await waState(),chip=document.getElementById('waCardStatus'),sub=document.getElementById('waCardSub');if(!chip||!sub)return;if(s?.c?.status==='connected'){chip.textContent='Conectado';chip.className='chip green';sub.textContent=`${s.groups.filter(g=>g.is_enabled).length} grupo(s) habilitado(s)`}else if(s?.c?.status==='pairing'){chip.textContent='Aguardando';chip.className='chip orange';sub.textContent='Pareamento em andamento'}else if(s?.c?.status==='degraded'){chip.textContent='Reconectando';chip.className='chip orange';sub.textContent='Gateway recuperando a sessão'}else if(s?.c){chip.textContent='Configurar';chip.className='chip orange';sub.textContent='WhatsApp ainda não conectado'}else{chip.textContent='Configurar';chip.className='chip orange';sub.textContent='Vincule seu WhatsApp e escolha grupos no Telegram'}}

async function syncWhatsAppGroups(connectionId,auto=false){
  const supabase=db();if(!supabase)return;
  modal(`<h3>WhatsApp automático</h3><div class="notice"><strong>🔄 Aguardando grupos…</strong><br>O gateway da Railway está conectado ao WhatsApp e enviará os grupos para o Afilia assim que o histórico/eventos chegarem. Não é necessário reconectar.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`);
  for(let i=0;i<30;i++){
    await sleep(2000);
    const s=await waState();
    if(!s||s.c?.id!==connectionId)return;
    if(s.groups.length){await refreshWaCard();return renderWhatsAppManager(s)}
    const body=document.getElementById('modalBody');if(!body)return;
  }
  const s=await waState();
  if(s?.groups?.length)return renderWhatsAppManager(s);
  modal(`<h3>WhatsApp automático</h3><div class="notice warn"><strong>A sessão está conectada, mas os grupos ainda não chegaram.</strong><br>O gateway continua ouvindo o WhatsApp em segundo plano. Use “Atualizar lista” daqui a pouco; não gere outro QR enquanto a sessão estiver conectada.</div><button class="btn primary full" onclick="syncWhatsAppGroups('${connectionId}')">🔄 Atualizar lista</button><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)
}
window.syncWhatsAppGroups=syncWhatsAppGroups;

function renderWhatsAppManager(s){if(!s)return;const c=s.c;if(!c||['disconnected','error','revoked'].includes(c.status)){modal(`<h3>WhatsApp automático</h3><p>Conecte seu WhatsApp como dispositivo vinculado. O gateway permanecerá online na Railway para receber histórico, grupos e enviar mensagens.</p><button class="btn primary full" onclick="startWhatsAppPairing()">📱 Gerar conexão por QR</button><button class="btn secondary full" onclick="closeModal()">Cancelar</button>`);return}const groups=s.groups;const rows=groups.length?groups.map(g=>`<div class="card"><div class="int"><div><h4>${escWa(g.display_name)}</h4><p>${g.is_enabled?'Aparece como botão no Telegram':'Oculto no Telegram'}</p></div><button class="chip ${g.is_enabled?'green':''}" onclick="toggleWhatsGroup('${g.id}',${!g.is_enabled})">${g.is_enabled?'Ativo':'Inativo'}</button></div></div>`).join(''):'<div class="emptySmall">Nenhum grupo recebido pelo gateway ainda.</div>';const connected=c.status==='connected';modal(`<h3>WhatsApp automático</h3><p>Status: <b>${escWa(c.status)}</b>${c.phone_masked?` • ${escWa(c.phone_masked)}`:''}</p><div class="notice ${connected?'good':'warn'}"><strong>${connected?'✅ Sessão conectada':'⏳ Pareamento/reconexão em andamento'}</strong><br>${connected?'A Railway mantém essa sessão ativa continuamente.':'Mantenha a janela do QR aberta até concluir.'}</div>${rows}<div class="actions">${connected?`<button class="btn primary full" onclick="syncWhatsAppGroups('${c.id}')">🔄 Atualizar grupos</button>`:`<button class="btn primary full" onclick="startWhatsAppPairing()">📱 Mostrar QR novo</button>`}<button class="btn danger full" onclick="disconnectWhatsApp()">Desvincular</button></div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}
async function openWhatsAppManager(){try{const s=await waState();if(!s){modal(`<h3>WhatsApp automático</h3><div class="notice warn"><strong>Não consegui carregar sua sessão.</strong><br>Atualize o Afilia e tente novamente.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`);return}if(s.c?.status==='connected'&&s.groups.length===0&&!waAutoWaitTried.has(s.c.id)){waAutoWaitTried.add(s.c.id);return syncWhatsAppGroups(s.c.id,true)}renderWhatsAppManager(s)}catch(e){modal(`<h3>WhatsApp automático</h3><div class="notice warn"><strong>Erro ao abrir a configuração.</strong><br>${escWa(e?.message||'Tente atualizar o aplicativo.')}</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}}
window.openWhatsAppManager=openWhatsAppManager;

async function startWhatsAppPairing(){const u=await me(),supabase=db();if(!u||!supabase)return;let{data:c}=await supabase.from('whatsapp_connections').select('*').eq('user_id',u.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!c){const r=await supabase.from('whatsapp_connections').insert({user_id:u.id,label:'WhatsApp principal',status:'pairing',pairing_method:'qr'}).select('*').single();if(r.error){alert('Não foi possível iniciar a conexão.');return}c=r.data}else{const r=await supabase.from('whatsapp_connections').update({status:'pairing',pairing_method:'qr',updated_at:new Date().toISOString()}).eq('id',c.id).eq('user_id',u.id);if(r.error){alert('Não foi possível preparar a conexão.');return}}
await supabase.from('whatsapp_pairing_requests').update({status:'expired',qr_payload:null,error_message:'Substituído por um novo QR.',updated_at:new Date().toISOString()}).eq('user_id',u.id).in('status',['waiting_gateway','qr_ready']);
const pr=await supabase.from('whatsapp_pairing_requests').insert({user_id:u.id,connection_id:c.id,status:'waiting_gateway'}).select('*').single();if(pr.error){alert('Não foi possível solicitar o QR.');return}
modal(`<h3>Vincular WhatsApp</h3><p>No WhatsApp, abra <b>Configurações → Dispositivos conectados → Conectar dispositivo</b>.</p><div id="waQrBox" class="notice"><strong>Preparando QR…</strong><br>A Railway está abrindo uma sessão nova e segura.</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`);
supabase.functions.invoke('whatsapp-pair',{body:{request_id:pr.data.id}}).then(async({error})=>{if(!error)return;const detail=await edgeErrorDetail(error,'Falha ao solicitar o pareamento');console.error('whatsapp-pair invoke',detail)}).catch(e=>console.error('whatsapp-pair invoke',e));
pollPairing(pr.data.id)}
window.startWhatsAppPairing=startWhatsAppPairing;

async function pollPairing(id){const supabase=db();if(!supabase)return;let lastQr='';for(let i=0;i<300;i++){await sleep(1000);const{data:p}=await supabase.from('whatsapp_pairing_requests').select('*').eq('id',id).maybeSingle();const box=document.getElementById('waQrBox');if(!box||!p)return;if(p.status==='qr_ready'&&p.qr_payload){if(lastQr!==p.qr_payload){lastQr=p.qr_payload;box.className='notice good';box.innerHTML=`<strong>Escaneie este QR no WhatsApp</strong><div id="waQrCanvas" style="background:white;padding:12px;margin:12px auto;width:max-content;border-radius:16px"></div><small>O QR é renovado automaticamente. Escaneie o que estiver visível agora e mantenha esta janela aberta.</small>`;try{const QR=await import('https://esm.sh/qrcode@1.5.4');const canvas=document.createElement('canvas');document.getElementById('waQrCanvas').appendChild(canvas);await QR.toCanvas(canvas,p.qr_payload,{width:230,margin:1})}catch{document.getElementById('waQrCanvas').textContent=p.qr_payload}}continue}if(p.status==='waiting_gateway'){box.className='notice';box.innerHTML=lastQr?'<strong>Atualizando a sessão…</strong><br>O gateway está renovando o QR ou finalizando o vínculo. Aguarde alguns segundos.':'<strong>Preparando QR…</strong><br>Abrindo a sessão no gateway persistente.';continue}if(p.status==='connected'){box.className='notice good';box.innerHTML='<strong>✅ WhatsApp conectado.</strong><br>A Railway ficou responsável pela sessão. Aguardando o histórico e os grupos…';await refreshWaCard();await sleep(1000);return syncWhatsAppGroups(p.connection_id,true)}if(['expired','failed'].includes(p.status)){box.className='notice warn';box.innerHTML=`<strong>Não foi possível concluir.</strong><br>${escWa(p.error_message||'Gere uma nova conexão e tente novamente.')}`;return}}}

async function toggleWhatsGroup(id,on){const u=await me(),supabase=db();if(!u||!supabase)return;await supabase.from('whatsapp_group_refs').update({is_enabled:on,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',u.id);await openWhatsAppManager();await refreshWaCard()}
window.toggleWhatsGroup=toggleWhatsGroup;
async function disconnectWhatsApp(){const u=await me(),supabase=db();if(!u||!supabase||!confirm('Desvincular este WhatsApp do Afilia? A sessão vinculada será encerrada.'))return;const s=await waState();if(!s?.c)return;modal(`<h3>WhatsApp automático</h3><div class="notice"><strong>Desvinculando…</strong><br>Encerrando a sessão no WhatsApp e removendo as credenciais salvas.</div>`);const{error}=await supabase.functions.invoke('whatsapp-disconnect',{body:{connection_id:s.c.id}});if(error){const detail=await edgeErrorDetail(error,'Não foi possível desvincular.');return modal(`<h3>WhatsApp automático</h3><div class="notice warn"><strong>Falha ao desvincular.</strong><br>${escWa(detail)}</div><button class="btn secondary full" onclick="closeModal()">Fechar</button>`)}waAutoWaitTried.delete(s.c.id);await refreshWaCard();renderWhatsAppManager(await waState())}
window.disconnectWhatsApp=disconnectWhatsApp;
window.refreshWaCard=refreshWaCard;
setTimeout(injectCard,900);window.addEventListener('hashchange',()=>setTimeout(injectCard,200));