import makeWASocket,{Browsers,DisconnectReason,fetchLatestWaWebVersion,useMultiFileAuthState}from'@whiskeysockets/baileys';
import{createClient}from'@supabase/supabase-js';
import pino from'pino';
import fs from'node:fs/promises';import path from'node:path';
import{createCipheriv,createDecipheriv,createHash,randomBytes}from'node:crypto';
import{createServer}from'node:http';
const U=process.env.SUPABASE_URL,K=process.env.SUPABASE_SERVICE_ROLE_KEY,ROOT=process.env.SESSION_ROOT||'./sessions',PORT=Number(process.env.PORT||8080);
if(!U||!K)throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required');
const db=createClient(U,K,{auth:{persistSession:false,autoRefreshToken:false}}),log=pino({level:process.env.LOG_LEVEL||'info'}),sessions=new Map(),localReady=new Set(),reconnectTimers=new Map(),persistTimers=new Map();
let keyCache=null,stopping=false;const now=()=>new Date().toISOString(),wait=ms=>new Promise(r=>setTimeout(r,ms)),isGroup=j=>typeof j==='string'&&j.endsWith('@g.us'),codeOf=e=>Number(e?.output?.statusCode||e?.statusCode||e?.data?.statusCode||0);await fs.mkdir(ROOT,{recursive:true});
async function assertPrivileged(){const{error}=await db.from('whatsapp_connections').select('id').limit(1);if(!error)return;if(String(error.message||'').includes('permission denied'))throw new Error('Railway Supabase key is anon/publishable; use sb_secret or service_role');throw error}
async function secret(n){const{data,error}=await db.rpc('service_get_platform_secret',{p_name:n});if(error)throw error;if(!data)throw new Error('missing '+n);return String(data)}
async function aesKey(){if(!keyCache)keyCache=createHash('sha256').update(await secret('platform.whatsapp.session_key')).digest();return keyCache}
async function seal(t){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',await aesKey(),iv),body=Buffer.concat([c.update(t,'utf8'),c.final()]);return iv.toString('base64')+'.'+Buffer.concat([body,c.getAuthTag()]).toString('base64')}
async function unseal(v){const[a,b]=String(v||'').split('.'),p=Buffer.from(b,'base64'),d=createDecipheriv('aes-256-gcm',await aesKey(),Buffer.from(a,'base64'));d.setAuthTag(p.subarray(-16));return Buffer.concat([d.update(p.subarray(0,-16)),d.final()]).toString('utf8')}
async function readFiles(root,dir=root,out={}){for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())await readFiles(root,p,out);else out[path.relative(root,p)]=(await fs.readFile(p)).toString('base64')}return out}
async function restore(cid,dir){const{data,error}=await db.rpc('service_get_whatsapp_session_blob',{p_connection_id:cid});if(error)throw error;if(!data)return false;const files=JSON.parse(await unseal(data));await fs.rm(dir,{recursive:true,force:true});await fs.mkdir(dir,{recursive:true});for(const[n,b]of Object.entries(files)){const p=path.join(dir,n);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,Buffer.from(String(b),'base64'))}localReady.add(cid);return true}
async function persist(cid,uid,dir){const payload=await seal(JSON.stringify(await readFiles(dir)));const{error}=await db.rpc('service_upsert_whatsapp_session_blob',{p_connection_id:cid,p_user_id:uid,p_encrypted_payload:payload});if(error)throw error}
function schedulePersist(cid,uid,dir){clearTimeout(persistTimers.get(cid));persistTimers.set(cid,setTimeout(()=>{persistTimers.delete(cid);persist(cid,uid,dir).catch(e=>log.error({cid,err:String(e)},'persist failed'))},500))}
async function setConn(id,p){const{error}=await db.from('whatsapp_connections').update({...p,updated_at:now()}).eq('id',id);if(error)throw error}
async function setPair(id,p){if(!id)return;const{error}=await db.from('whatsapp_pairing_requests').update({...p,updated_at:now()}).eq('id',id);if(error)throw error}
async function upsertGroup(cid,uid,jid,name=''){if(!isGroup(jid))return;const{data:old,error}=await db.from('whatsapp_group_refs').select('id,display_name').eq('connection_id',cid).eq('external_group_ref',jid).maybeSingle();if(error)throw error;const display=name||old?.display_name||'Grupo WhatsApp';if(old){const{error:e}=await db.from('whatsapp_group_refs').update({display_name:display,updated_at:now()}).eq('id',old.id);if(e)throw e}else{const{error:e}=await db.from('whatsapp_group_refs').insert({user_id:uid,connection_id:cid,external_group_ref:jid,display_name:display,role:'destination',is_enabled:false});if(e)throw e;log.info({cid,jid,display},'group discovered')}}
async function discover(cid,uid,sock,jid,hint='',source='event'){if(!isGroup(jid))return;let name=hint;if(!name){try{name=(await sock.groupMetadata(jid))?.subject||''}catch{}}await upsertGroup(cid,uid,jid,name||'Grupo WhatsApp');log.debug({cid,jid,source},'group candidate')}
async function auditHistory(uid,cid,meta){try{await db.from('audit_events').insert({user_id:uid,event_type:'whatsapp.history_probe',entity_type:'whatsapp_connection',entity_id:cid,redacted_metadata:{...meta,at:now()}})}catch{}}
function wireEvents(cid,uid,sock){sock.ev.on('messaging-history.set',ev=>{(async()=>{try{let g=0;for(const chat of ev?.chats||[]){if(isGroup(chat?.id))g++;await discover(cid,uid,sock,chat?.id,chat?.name||chat?.displayName||'','history_chat')}for(const msg of ev?.messages||[]){await discover(cid,uid,sock,msg?.key?.remoteJid,'','history_message');await discover(cid,uid,sock,msg?.key?.remoteJidAlt,'','history_alt')}await auditHistory(uid,cid,{source:'history',chats:ev?.chats?.length||0,messages:ev?.messages?.length||0,group_chats:g,progress:ev?.progress??null});log.info({cid,chats:ev?.chats?.length||0,messages:ev?.messages?.length||0,groupChats:g,progress:ev?.progress},'history received')}catch(e){log.error({cid,err:String(e)},'history handler failed')}})()});
sock.ev.on('chats.upsert',chats=>{(async()=>{try{for(const chat of chats||[])await discover(cid,uid,sock,chat?.id,chat?.name||chat?.displayName||'','chat_upsert')}catch(e){log.warn({cid,err:String(e)},'chats handler failed')}})()});
sock.ev.on('messages.upsert',ev=>{(async()=>{try{for(const msg of ev?.messages||[]){await discover(cid,uid,sock,msg?.key?.remoteJid,'','message');await discover(cid,uid,sock,msg?.key?.remoteJidAlt,'','message_alt')}}catch(e){log.warn({cid,err:String(e)},'messages handler failed')}})()});
sock.ev.on('groups.upsert',gs=>{(async()=>{try{for(const g of gs||[])await discover(cid,uid,sock,g?.id,g?.subject||'','groups_upsert')}catch(e){log.warn({cid,err:String(e)},'groups upsert failed')}})()});
sock.ev.on('groups.update',gs=>{(async()=>{try{for(const g of gs||[])await discover(cid,uid,sock,g?.id,g?.subject||'','groups_update')}catch(e){log.warn({cid,err:String(e)},'groups update failed')}})()});
sock.ev.on('group-participants.update',e=>discover(cid,uid,sock,e?.id,'','participants').catch(()=>{}))}
function scheduleReconnect(cid,uid,pairId=null,delay=1500){if(stopping||reconnectTimers.has(cid))return;reconnectTimers.set(cid,setTimeout(()=>{reconnectTimers.delete(cid);startConnection(cid,uid,{pairId,fresh:false}).catch(e=>{log.error({cid,err:String(e)},'reconnect failed');scheduleReconnect(cid,uid,pairId,4000)})},delay))}
async function startConnection(cid,uid,{pairId=null,fresh=false}={}){const prev=sessions.get(cid);if(prev){try{prev.sock.end(undefined)}catch{}sessions.delete(cid)}const dir=path.join(ROOT,cid);if(fresh){await fs.rm(dir,{recursive:true,force:true});await fs.mkdir(dir,{recursive:true});localReady.add(cid)}else if(!localReady.has(cid)){if(!await restore(cid,dir))throw new Error('session_not_found')}
const{state,saveCreds}=await useMultiFileAuthState(dir),{version}=await fetchLatestWaWebVersion(),sock=makeWASocket({auth:state,version,logger:log.child({cid}),browser:Browsers.ubuntu('Chrome'),printQRInTerminal:false,markOnlineOnConnect:false,syncFullHistory:true,fireInitQueries:true,shouldSyncHistoryMessage:()=>true,keepAliveIntervalMs:20000,connectTimeoutMs:60000,defaultQueryTimeoutMs:60000});const s={sock,uid,dir,open:false,pairId};sessions.set(cid,s);wireEvents(cid,uid,sock);
sock.ev.on('creds.update',async()=>{try{await saveCreds();schedulePersist(cid,uid,dir)}catch(e){log.error({cid,err:String(e)},'creds update failed')}});
sock.ev.on('connection.update',u=>{(async()=>{try{if(u.qr&&pairId)await setPair(pairId,{status:'qr_ready',qr_payload:u.qr,error_message:null});if(u.connection==='open'){s.open=true;await persist(cid,uid,dir);const raw=String(sock.user?.id||''),digits=raw.split(':')[0].replace(/\D/g,'');await setConn(cid,{status:'connected',pairing_method:'qr',phone_masked:digits?`***${digits.slice(-4)}`:null,session_secret_configured:true,last_connected_at:now(),last_heartbeat_at:now()});if(pairId)await setPair(pairId,{status:'connected',qr_payload:null,error_message:null});log.info({cid,pairId,version},'connection open')}if(u.connection==='close'){s.open=false;if(sessions.get(cid)?.sock===sock)sessions.delete(cid);const code=codeOf(u.lastDisconnect?.error),logged=code===DisconnectReason.loggedOut||code===401;await setConn(cid,{status:logged?'disconnected':'reconnecting',last_heartbeat_at:now()});log.warn({cid,code,logged,pairId},'connection closed');if(logged){localReady.delete(cid);if(pairId)await setPair(pairId,{status:'failed',qr_payload:null,error_message:'WhatsApp desconectado'})}else scheduleReconnect(cid,uid,pairId,[408,428,503,515].includes(code)?900:2200)}}catch(e){log.error({cid,err:String(e)},'connection handler failed')}})()});return sock}
async function consumePairings(){const{data:reqs=[],error}=await db.from('whatsapp_pairing_requests').select('id,user_id,connection_id,expires_at').eq('status','waiting_gateway').order('created_at').limit(5);if(error)throw error;for(const p of reqs){if(new Date(p.expires_at)<new Date()){await setPair(p.id,{status:'expired'});continue}const cur=sessions.get(p.connection_id);if(cur?.pairId===p.id)continue;await setConn(p.connection_id,{status:'pairing',pairing_method:'qr'});startConnection(p.connection_id,p.user_id,{pairId:p.id,fresh:true}).catch(async e=>{log.error({pair:p.id,err:String(e)},'pair start failed');await setPair(p.id,{status:'failed',error_message:String(e?.message||e).slice(0,180)})})}}
async function restoreConnections(){const{data:rows=[],error}=await db.from('whatsapp_connections').select('id,user_id,status,session_secret_configured').in('status',['connected','reconnecting']);if(error)throw error;for(const c of rows)if(c.session_secret_configured&&!sessions.has(c.id))startConnection(c.id,c.user_id,{fresh:false}).catch(e=>{log.error({cid:c.id,err:String(e)},'restore failed');scheduleReconnect(c.id,c.user_id,null,4000)})}
async function processJobs(){const{data:jobs=[],error}=await db.from('whatsapp_outbound_jobs').select('id,user_id,connection_id,group_ref_id,offer_id,message_text,attempts,whatsapp_group_refs(external_group_ref)').eq('status','queued').order('created_at').limit(20);if(error)throw error;for(const j of jobs){const s=sessions.get(j.connection_id),jid=j.whatsapp_group_refs?.external_group_ref;if(!s?.open||!isGroup(jid))continue;const attempts=Number(j.attempts||0)+1,{data:lock}=await db.from('whatsapp_outbound_jobs').update({status:'processing',started_at:now(),attempts,updated_at:now(),last_error:null}).eq('id',j.id).eq('status','queued').select('id').maybeSingle();if(!lock)continue;try{const sent=await s.sock.sendMessage(jid,{text:j.message_text});await db.from('whatsapp_outbound_jobs').update({status:'sent',sent_at:now(),external_message_id:sent?.key?.id||null,updated_at:now(),last_error:null}).eq('id',j.id);if(j.offer_id)await db.from('offers').update({status:'published',published_at:now(),updated_at:now()}).eq('id',j.offer_id).eq('user_id',j.user_id)}catch(e){await db.from('whatsapp_outbound_jobs').update({status:attempts>=3?'failed':'queued',last_error:String(e?.message||e).slice(0,500),updated_at:now()}).eq('id',j.id)}}}
async function heartbeat(){for(const[id,s]of sessions)if(s.open)await setConn(id,{last_heartbeat_at:now()})}
createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/'||req.url==='/health'){res.writeHead(200);res.end(JSON.stringify({ok:true,service:'afilia-whatsapp-worker-v4',open:[...sessions.values()].filter(s=>s.open).length,sessions:sessions.size,at:now()}));return}res.writeHead(404);res.end('{}')}).listen(PORT,'0.0.0.0',()=>log.info({PORT},'health server'));
process.on('SIGTERM',()=>{stopping=true;process.exit(0)});process.on('SIGINT',()=>{stopping=true;process.exit(0)});
await assertPrivileged();await restoreConnections();log.info('Afilia WhatsApp worker v4 started');for(;;){try{await consumePairings();await restoreConnections();await processJobs();await heartbeat()}catch(e){log.error({err:String(e)},'loop failed')}await wait(3000)}
